/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author isabe
 */
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;

public class VistaPrincipal extends VistaBase {

    private ActionListener listenerSupermercado;
    private ActionListener listenerOnline;
    private ActionListener listenerLista;
    private ActionListener listenerVoz;

    private JButton ultimoBoton = null;

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        super("Asistente de Compras");
        setLocationRelativeTo(null);
        lectorVoz.hablar("Bienvenido. Que deseas hacer hoy Recuerda un click para escuchar, otro para realizar acciones");
    }

    @Override
    protected void initComponentes() {
        initComponents();
        configurarEstilos();
    }

    private void configurarEstilos() {
        chkVoz.setSelected(true);
        chkVoz.setOpaque(false);

        aplicarEstiloBoton(btnSupermercado, new Color(255, 255, 255), "Ir al supermercado");
        aplicarEstiloBoton(btnOnline, new Color(255, 255, 255), "Comprar en linea");
        aplicarEstiloBoton(btnLista, new Color(255, 255, 255), "Mi lista de compras");
    }

    private void aplicarEstiloBoton(JButton btn, Color color, String textoVoz) {
        btn.setBackground(color);
        btn.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

        for (ActionListener al : btn.getActionListeners()) {
            btn.removeActionListener(al);
        }

        btn.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                btn.setBackground(color.darker());

            }

            @Override
            public void mouseExited(MouseEvent e) {
                btn.setBackground(color);
            }

            @Override
            public void mouseClicked(MouseEvent e) {
                if (ultimoBoton != btn) {
                    ultimoBoton = btn;
                    if (chkVoz.isSelected()) {
                        lectorVoz.hablar(textoVoz);
                    }
                    return;
                }

                ultimoBoton = null;

                if (btn == btnSupermercado && listenerSupermercado != null) {
                    listenerSupermercado.actionPerformed(new ActionEvent(btn, ActionEvent.ACTION_PERFORMED, ""));
                }
                if (btn == btnOnline && listenerOnline != null) {
                    listenerOnline.actionPerformed(new ActionEvent(btn, ActionEvent.ACTION_PERFORMED, ""));
                }
                if (btn == btnLista && listenerLista != null) {
                    listenerLista.actionPerformed(new ActionEvent(btn, ActionEvent.ACTION_PERFORMED, ""));
                }
            }
        });
    }

    public void addBtnSupermercadoListener(ActionListener l) {
        this.listenerSupermercado = l;
    }

    public void addBtnOnlineListener(ActionListener l) {
        this.listenerOnline = l;
    }

    public void addBtnListaListener(ActionListener l) {
        this.listenerLista = l;
    }

    public void addChkVozListener(ActionListener l) {
        this.listenerVoz = l;
    }

    public boolean isVozActiva() {
        return chkVoz.isSelected();
    }
    
    public void setVozActiva(boolean activa) {
        chkVoz.setSelected(activa);
        lectorVoz.setActivo(activa);
        if (activa) {
            lectorVoz.hablar("Voz activada");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblInstruccion = new javax.swing.JLabel();
        btnSupermercado = new javax.swing.JButton();
        btnOnline = new javax.swing.JButton();
        btnLista = new javax.swing.JButton();
        chkVoz = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        lblTitulo.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 48)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 51, 0));
        lblTitulo.setText("ASISTENTE DE COMPRAS");

        lblInstruccion.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        lblInstruccion.setText("¿Qué deseas hacer?");

        btnSupermercado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSupermercado.setForeground(new java.awt.Color(0, 51, 0));
        btnSupermercado.setText("Ir al supermercado");
        btnSupermercado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSupermercado.setPreferredSize(new java.awt.Dimension(320, 64));
        btnSupermercado.setRequestFocusEnabled(false);
        btnSupermercado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupermercadoActionPerformed(evt);
            }
        });

        btnOnline.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnOnline.setForeground(new java.awt.Color(0, 51, 0));
        btnOnline.setText("Comprar en linea ");
        btnOnline.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnOnline.setPreferredSize(new java.awt.Dimension(320, 64));
        btnOnline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOnlineActionPerformed(evt);
            }
        });

        btnLista.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnLista.setForeground(new java.awt.Color(0, 51, 0));
        btnLista.setText("Mi lista de compras");
        btnLista.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnLista.setPreferredSize(new java.awt.Dimension(320, 64));
        btnLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaActionPerformed(evt);
            }
        });

        chkVoz.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chkVoz.setText("Activar voz");
        chkVoz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkVozActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 0));
        jLabel2.setText("🛒");

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 0));
        jLabel1.setText("🚛");

        jLabel3.setFont(new java.awt.Font("Segoe UI Emoji", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 0));
        jLabel3.setText("📋");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(232, 232, 232)
                .addComponent(lblInstruccion)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(lblTitulo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(chkVoz, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnOnline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSupermercado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(56, 112, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblTitulo)
                .addGap(26, 26, 26)
                .addComponent(lblInstruccion)
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(btnSupermercado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnOnline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(chkVoz, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSupermercadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupermercadoActionPerformed
        // TODO add your handling code here:
        if (listenerSupermercado != null) {
            listenerSupermercado.actionPerformed(evt);
        }
    }//GEN-LAST:event_btnSupermercadoActionPerformed

    private void btnOnlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOnlineActionPerformed
        // TODO add your handling code here:
        if (listenerOnline != null) {
            listenerOnline.actionPerformed(evt);
        }
    }//GEN-LAST:event_btnOnlineActionPerformed

    private void btnListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaActionPerformed
        // TODO add your handling code here:
        if (listenerLista != null) {
            listenerLista.actionPerformed(evt);
        }
    }//GEN-LAST:event_btnListaActionPerformed

    private void chkVozActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkVozActionPerformed
        // TODO add your handling code here:
        if (listenerVoz != null) {
            listenerVoz.actionPerformed(evt);
        }
        lectorVoz.setActivo(chkVoz.isSelected());
        if (chkVoz.isSelected()) {
            lectorVoz.hablar("Voz activada");
        }
    }//GEN-LAST:event_chkVozActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLista;
    private javax.swing.JButton btnOnline;
    private javax.swing.JButton btnSupermercado;
    private javax.swing.JCheckBox chkVoz;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblInstruccion;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
